CUISINES = {
	u'Cajun & Creole': 'Caribbean',
 	u'Indian': 'Indian',
 	u'Hawaiian': 'Hawaiian',
	u'French': 'French',
	u'Thai': 'Thai', 
	u'Cuban': 'Cuban', 
	u'Portuguese': 'Portuguese', 
	u'Southwestern': 'Tex-Mex', 
	u'Greek': 'Greek', 
	u'American': 'American', 
	u'Italian': 'Italian', 
	u'Southern & Soul Food': 'Soul Food', 
	u'Irish': 'Irish', 
	u'Mexican': 'Mexican', 
	u'Chinese': 'Chinese', 
	u'German': 'German', 
	u'Mediterranean': 'Mediterranean', 
	u'Japanese': 'Japanese', 
	u'Moroccan': 'Moroccan', 
	u'Asian': 'Asian', 
	u'Spanish': 'Spanish', 
	u'Barbecue': 'Barbecue'}